SELECT * FROM simulation;
SELECT * FROM simulation_model;
SELECT * FROM model_benchmark;
SELECT * FROM model_specs_structure;
SELECT * FROM model_structure_perfomance;
SELECT * FROM structure_max_base_shear;
SELECT * FROM structure_max_drift_per_floor;
SELECT * FROM structure_abs_acceleration;
SELECT * FROM structure_relative_displacements;	
SELECT * FROM simulation_sm_input